<?php

/**
 *  Convert the labels into a Javascript array
 *  
 *  @author David Walker
 *  @copyright 2011 California State University
 *  @version
 *  @package Xerxes
 *  @link http://xerxes.calstate.edu
 *  @license
 */

?>
xerxes_labels = new Array();
<?php 
	
	foreach ( $this->getVariable('labels')->getLabels() as $name => $value )
	{
		$value = str_replace('"', '\\"', $value);
		$value = str_replace("\n", " ", $value);
		echo "xerxes_labels['$name'] = \"$value\";\n";
	}
?>