<?php

/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/*
 *  Convert the labels into a Javascript array
 *  
 *  @author David Walker <dwalker@calstate.edu>
 */

?>
xerxes_labels = new Array();
<?php 
	
	foreach ( $this->getVariable('labels')->getLabels() as $name => $value )
	{
		$value = str_replace('"', '\\"', $value);
		$value = str_replace("\n", " ", $value);
		echo "xerxes_labels['$name'] = \"$value\";\n";
	}
?>